model:
  model_path: '../Model/VORT/'
  result_path: '../Result/VORT/'
  unet:
    in_channels: 2
    out_channels: 1
    ch: 32
    scale: 3
    num_blocks: 1 
  coordnet:
    in_features: 4
    out_features: 1
    num_res: 10
    init_features: 108
  beta_schedule:
    linear_start: 1e-4
    linear_end: 2e-2
    train:
      n_timestep: 1000
    inf:
      n_timestep: 100
  diffusion:
    params:
      model_mean_type: START_X
      model_var_type: FIXED_LARGE
      loss_type: MSE

train:
  epochs: 50000
  optimizer:
    lr: 2e-5 

inf:
  epochs: 50000

task: 'SSR'

data:
  dataset: 'Combustion'
  var1: 'VORT'
  num_samples: 3
  num: 100
  factor: 4
  croptimes: 1
  sampling: 'uniform'
  cropsize: [160,240,40] #[160,240,40]